# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py


#### 1. Import the numpy package under the name `np` (★☆☆)

In [205]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [206]:
print(np.__version__ )
print(np.show_config())

2.0.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
     

#### 3. Create a null vector of size 10 (★☆☆)

In [207]:
q03= np.zeros(10)
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [208]:
q03.itemsize * q03.size 
print(f" bytes: {(q03.itemsize * q03.size):.2f}")
answer(4)

 bytes: 80.00
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [209]:
print(np.info('add'))

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [210]:
q6 = np.zeros(10)
q6[4] = 1
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [211]:
q07 = np.arange(10,50)
print(q07)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [212]:
q07 = np.arange(10,50)
q08 = q07[-1::-1]
print(q08)
answer(8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [213]:
q = np.arange(0,9)
q.reshape(3,3)
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [214]:
q10 = np.array([1,2,0,0,4,0])
print(np.where(q10!=0))
q10.nonzero()



(array([0, 1, 4]),)


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [215]:
print(np.identity(3))
Z = np.eye(3)
print(Z)
answer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [216]:
np.random.random((3,3,3))

array([[[0.55313696, 0.54250747, 0.04263811],
        [0.3217623 , 0.52284295, 0.30453802],
        [0.63950785, 0.37404735, 0.11582903]],

       [[0.19074766, 0.19012456, 0.93354012],
        [0.77912988, 0.36954955, 0.11735069],
        [0.13798124, 0.18426959, 0.1960046 ]],

       [[0.1328722 , 0.72541735, 0.79017709],
        [0.36938046, 0.95673976, 0.75047907],
        [0.17925802, 0.85913932, 0.92253382]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [217]:
x = np.random.random((10,10))
print(x)
print(x.max())
print(x.min())
answer(13)

[[0.5356884  0.19970351 0.95279291 0.78845603 0.33637208 0.83668288
  0.90010426 0.60325573 0.65232376 0.4360711 ]
 [0.18704662 0.74223279 0.75102036 0.72531017 0.1582499  0.34174937
  0.27265131 0.49930978 0.01997646 0.04370265]
 [0.19843955 0.22568349 0.1110245  0.62844921 0.54899122 0.06648554
  0.28842652 0.52611384 0.90131102 0.47807579]
 [0.2997909  0.64446175 0.70444791 0.88973462 0.1060563  0.18951852
  0.04282013 0.14922818 0.23097535 0.56670181]
 [0.74723644 0.61212663 0.72331477 0.24704051 0.41811901 0.43110875
  0.08781018 0.45739    0.48355426 0.84240455]
 [0.21836444 0.94322676 0.84828044 0.30892248 0.73835158 0.9449435
  0.96382683 0.50599369 0.68488658 0.69363816]
 [0.26488599 0.40397146 0.12447929 0.08133461 0.21305891 0.42253188
  0.48323977 0.87913476 0.84276441 0.22724333]
 [0.43921751 0.2368526  0.13120466 0.00504696 0.46739318 0.30285989
  0.47897582 0.52796799 0.10662105 0.80787596]
 [0.02074879 0.90718711 0.1173121  0.93612524 0.29230504 0.99709993
  0.26712877 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [218]:
q14Pre = np.random.random(30)
print(q14Pre.mean())
print(q14Pre)
answer(14)


0.5407146437216871
[0.23576056 0.57751078 0.2678395  0.85691323 0.13603108 0.62973055
 0.83345812 0.51649403 0.29425972 0.959915   0.58908736 0.17243051
 0.40844824 0.89611808 0.27495637 0.75907438 0.79557623 0.95698518
 0.34090921 0.30690744 0.53969757 0.64258226 0.05836693 0.56126313
 0.22491053 0.8300291  0.46696346 0.64832697 0.46199912 0.97889468]
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [219]:
q15 = np.ones((3,3))
q15[1,1] = 0
print(q15)
answer(15)

q15a = np.ones((10,10))
q15a[1:-1,1:-1] = 0
print(q15a)





[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [220]:
q16 = np.random.random((5,5))
q16[0,:] = 0 
q16[-1,:] = 0 
q16[:,0] = 0 
q16[:,-1] = 0 
print(q16)
answer(16)

[[0.         0.         0.         0.         0.        ]
 [0.         0.7428913  0.59466555 0.6192302  0.        ]
 [0.         0.7406637  0.71190676 0.47645739 0.        ]
 [0.         0.38053784 0.88749314 0.22824438 0.        ]
 [0.         0.         0.         0.         0.        ]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [221]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [222]:
q18 = np.zeros((5,5))
answer(18)


Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [223]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
print(Z)
Z[::2,1::2] = 1
print(Z)


[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [224]:
numOfElements = 6*7*8
print(f"Number of Elements: {numOfElements}" )
elementsIndexed = np.arange(1,numOfElements+1)
newArray  =  elementsIndexed.reshape(6,7,8)
print(np.where(newArray==100))
print(np.unravel_index(99,(6,7,8)))
answer(20)

Number of Elements: 336
(array([1]), array([5]), array([3]))
(np.int64(1), np.int64(5), np.int64(3))
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [225]:
a1  = np.array([[0,1],[1,0]])
a2  = np.tile(a1,(4,4))
print(a2)
answer(21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [226]:
a = np.random.random((5,5))
Z = (a - np.mean (a)) / (np.std (a))
print(Z)

answer(22)

[[-0.088182   -1.10454465  1.32192095  1.37316134 -0.9674647 ]
 [-1.10595179 -0.54699227 -0.66170378 -0.90946699  1.84333543]
 [-1.4575961   1.15044606 -0.30655513 -0.16567034  0.57170569]
 [-1.45459737 -0.64264118  0.63634217  0.62047451  0.34275709]
 [ 0.47456179  1.99429128  0.53829417 -0.46977469 -0.98614949]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [227]:
x = np.array([1,2,3,4]).astype(np.uint8)
print(x)
np.dtype([])

answer(23)

[1 2 3 4]
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [228]:
x = np.random.random((5,3))
y = np.random.random((3,2))
print(np.matmul(x,y))



[[0.57802811 0.08144493]
 [1.18864255 0.29356848]
 [1.09808531 0.3024562 ]
 [1.50006295 0.40936924]
 [0.91199801 0.21392181]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [229]:
x = np.arange(0,91)
x[(3<x) & (x<8)] = -1  * x[(3<x) & (x<8)]
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [230]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [235]:
answer(27)
Z= 78
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [241]:
answer(29)
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
[-1.14254691 -3.71169647  2.19938437  9.62699196  6.94729471  4.05552698
 -3.79426038  7.70249521  2.44138107  9.39463036]
[-2. -4.  3. 10.  7.  5. -4.  8.  3. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
print(np.union1d(Z1,Z2))


[3 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [246]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [248]:
np.emath.sqrt(-1)

np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [252]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2025-03-21
2025-03-22
2025-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [253]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [254]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [255]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [261]:
X = np.arange(0,5)
print(X)
np.tile(X,(5,1))


[0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [262]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [271]:
answer(39)
X = np.linspace(0,1,12) 
Y = X[1:-1]
print(X)
print(Y)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [277]:
X = np.random.random(10)
print(np.sort(X))
X.sort()
print(X)
answer(40)

[0.28927245 0.37618564 0.40360842 0.49151679 0.60142585 0.61769308
 0.74071321 0.9274542  0.93367943 0.99825682]
[0.28927245 0.37618564 0.40360842 0.49151679 0.60142585 0.61769308
 0.74071321 0.9274542  0.93367943 0.99825682]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [278]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [280]:
A = np.random.random(10)
B = np.random.random(10)
print(A==B)
answer(42)

[False False False False False False False False False False]
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [281]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [292]:
ctsn = np.random.random((10,2))
plr = ctsn.copy()
plr[:,0] = np.sqrt(np.pow(ctsn[:,0],2) + np.pow(ctsn[:,1],2))
plr[:,1] = np.arctan(ctsn[:,1],ctsn[:,0])

print(ctsn)
print(plr)

answer(44)

[[0.30177659 0.31128391]
 [0.0717269  0.07185015]
 [0.0415311  0.04155499]
 [0.62086506 0.71521577]
 [0.45369271 0.4876176 ]
 [0.23715606 0.24170454]
 [0.7664575  0.96281846]
 [0.72351553 0.88330701]
 [0.77203983 0.97363397]
 [0.14805553 0.14914691]]
[[0.38855269 0.30177659]
 [0.36815859 0.0717269 ]
 [0.89073957 0.0415311 ]
 [0.78573076 0.62086506]
 [1.08056719 0.45369271]
 [0.86176184 0.23715606]
 [1.07280419 0.7664575 ]
 [0.99753893 0.72351553]
 [1.00622599 0.77203983]
 [0.15243901 0.14805553]]
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [294]:
x = np.random.random(10)
print(x)
x[x==x.max()] = 0 
print(x)
answer(45)

[0.8296205  0.66277918 0.04263834 0.99310171 0.06828467 0.59435862
 0.36775572 0.21219653 0.80595305 0.59748232]
[0.8296205  0.66277918 0.04263834 0.         0.06828467 0.59435862
 0.36775572 0.21219653 0.80595305 0.59748232]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [300]:
X = zeros((100,2))
x = np.linspace(0,1,10)
y = np.linspace(0,1,10)
print(x)
print(y)
p=0
for ax in x :
    for ay in y:
        
        X[p,0] = ax
        X[p,1] = ay
        p = p+1 
print(X)

answer(46)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.         0.        ]
 [0.         0.11111111]
 [0.         0.22222222]
 [0.         0.33333333]
 [0.         0.44444444]
 [0.         0.55555556]
 [0.         0.66666667]
 [0.         0.77777778]
 [0.         0.88888889]
 [0.         1.        ]
 [0.11111111 0.        ]
 [0.11111111 0.11111111]
 [0.11111111 0.22222222]
 [0.11111111 0.33333333]
 [0.11111111 0.44444444]
 [0.11111111 0.55555556]
 [0.11111111 0.66666667]
 [0.11111111 0.77777778]
 [0.11111111 0.88888889]
 [0.11111111 1.        ]
 [0.22222222 0.        ]
 [0.22222222 0.11111111]
 [0.22222222 0.22222222]
 [0.22222222 0.33333333]
 [0.22222222 0.44444444]
 [0.22222222 0.55555556]
 [0.22222222 0.66666667]
 [0.22222222 0.77777778]
 [0.22222222 0.88888889]
 [0.22222222 1.        ]
 [0.33333333 0.        ]

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [15]:

X = np.random.random(5)
Y = np.random.random(5)
print(X.size)
C = np.zeros((X.size, Y.size))
# print(C)
for xIn ,xx in enumerate(X):
    for yIn, yy in enumerate(Y):
        C[xIn,yIn] = 1/(xx - yy)

print(C)
# answer(47)
print("----------")
D = 1/np.subtract.outer(X, Y)
print(D)

5
[[ -1.90570186  -3.23398324  -1.26020149  -1.06686584  -1.93496528]
 [ -5.22360065  41.51785152  -2.17286591  -1.65556676  -5.44950469]
 [461.22908593   4.59362549  -3.75073052  -2.43655333  98.97036262]
 [  2.69528842   1.70490582   9.78139004 -24.05805483   2.63884465]
 [ 34.69230499   4.09249545  -4.16739574  -2.60580146  27.20292638]]
----------
[[ -1.90570186  -3.23398324  -1.26020149  -1.06686584  -1.93496528]
 [ -5.22360065  41.51785152  -2.17286591  -1.65556676  -5.44950469]
 [461.22908593   4.59362549  -3.75073052  -2.43655333  98.97036262]
 [  2.69528842   1.70490582   9.78139004 -24.05805483   2.63884465]
 [ 34.69230499   4.09249545  -4.16739574  -2.60580146  27.20292638]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [16]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [18]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [31]:
A = np.random.random((3,4))
print(A)
D = np.abs(A-5)
print(D)
print(np.argmin(D))
print(np.unravel_index(np.argmin(D),shape=A.shape))


[[0.19909009 0.18564779 0.18186599 0.9310921 ]
 [0.4404745  0.29740795 0.3403012  0.8347002 ]
 [0.61108924 0.1402107  0.2282858  0.74021232]]
[[4.80090991 4.81435221 4.81813401 4.0689079 ]
 [4.5595255  4.70259205 4.6596988  4.1652998 ]
 [4.38891076 4.8597893  4.7717142  4.25978768]]
3
(np.int64(0), np.int64(3))


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [32]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [35]:
XY = np.random.random((100,2))*10

answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [36]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [37]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [38]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [39]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [40]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
Y = np.random.random((3,5))
print(Y)
X = np.mean(Y, axis=1,
answer(58)



[[0.60384363 0.16364407 0.35928755 0.10094544 0.84006834]
 [0.51768221 0.61272674 0.38615858 0.91796716 0.62468632]
 [0.5793116  0.43844862 0.49110733 0.48701413 0.48282466]]
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)